Basic splash screen implemented
Flutter-Buddies/Punk-Messenger pull request #11
Opened 2021-02-06 19:35 UTC by Codeek89

PS. I had to change the sdk version since vsync parameter in the "welcome_screen" animation couldn't be found by android studio.

2021-02-07 21:10 UTC, hanskokx requested changes

2021-02-07 21:10 UTC, hanskokx commented on lib/presentation/screens/splash_screen.dart
> +    Timer(Duration(seconds: 2),
Is this an arbitrary value? It should only show the splash screen as long as the application is loading.

2021-02-07 21:10 UTC, hanskokx commented on lib/presentation/screens/splash_screen.dart
> +        child: Container(
Container in a container? Why not Expanded()?

2021-02-08 09:50 UTC, Codeek89 commented on lib/presentation/screens/splash_screen.dart
> +        child: Container(
you're right I didn't think about it

2021-02-10 03:50 UTC, Rift3000 commented on lib/presentation/screens/splash_screen.dart
> +    Timer(Duration(seconds: 2),
I agree

2021-02-10 03:51 UTC, Rift3000 commented on lib/presentation/screens/splash_screen.dart
> +        child: Container(
Looking forward to your next PR

2021-02-11 15:07 UTC, Codeek89 commented on lib/presentation/screens/splash_screen.dart
> +    Timer(Duration(seconds: 2),
okok, so I have to work with xml, for what concerns the android part.

2021-02-12 19:19 UTC, Codeek89 commented
I made a new commit

2021-02-15 20:57 UTC, hanskokx approved these changes

2021-02-15 21:18 UTC, Rift3000 approved these changes

2021-02-15 21:18 UTC, merged

2021-02-15 21:18 UTC, Rift3000 commented
Nicely done

2021-02-15 23:30 UTC, Codeek89 commented
Thank youuu